# Generated by Django 5.0.3 on 2024-04-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datamanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=30)),
                ('Value', models.BooleanField()),
                ('UserType', models.CharField(blank=True, choices=[('MODERATOR', 'Moderator'), ('REGULAR', 'Regular user')], max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiogasMachineModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.IntegerField(null=True)),
                ('Sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=9)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Registered', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=False)),
                ('Machines', models.ManyToManyField(to='datamanagement.machine')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiogasMachineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.IntegerField(null=True)),
                ('Sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=9)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Registered', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=False)),
                ('Machines', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanagement.machine')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarningContent', models.CharField(max_length=255)),
                ('WarningType', models.CharField(choices=[('ELE', 'Electrical'), ('ENV', 'Environment'), ('OPE', 'Operational'), ('MISC', 'Miscellaneous')], default='MISC', max_length=11)),
                ('WarningResolution', models.CharField(choices=[('T', 'Resolved'), ('F', 'Unresolved')], default='F', max_length=2)),
                ('Machines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanagement.machine')),
            ],
        ),
    ]
