# Generated by Django 5.0.3 on 2024-04-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0001_initial'),
        ('usermanagement', '0002_remove_warnings_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='Machines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanagement.machine'),
        ),
    ]
