# Generated by Django 5.0.3 on 2024-06-18 04:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_warnings_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasmachineuser',
            name='Avatar',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos/profiles'), upload_to=''),
        ),
    ]
