# Generated by Django 5.0.3 on 2024-06-18 04:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_biogasmachineuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasmachinemoderator',
            name='Avatar',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos/profiles'), upload_to=''),
        ),
    ]
