# Generated by Django 5.0.3 on 2024-06-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_biogasmachinemoderator_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biogasmachinemoderator',
            name='Avatar',
        ),
        migrations.RemoveField(
            model_name='biogasmachineuser',
            name='Avatar',
        ),
    ]
