# Generated by Django 5.0.3 on 2024-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='Id_parameter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='MachineIDString',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
