# Generated by Django 5.0.3 on 2024-07-10 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0002_alter_parameters_id_parameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParamID', models.CharField(max_length=100)),
                ('Value', models.FloatField()),
                ('MachineID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanagement.machine')),
            ],
        ),
    ]
