# Generated by Django 5.0.3 on 2024-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0003_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholds',
            name='MachineID',
            field=models.CharField(max_length=100),
        ),
    ]
