# Generated by Django 5.0.3 on 2024-07-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0004_alter_thresholds_machineid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thresholds',
            old_name='MachineID',
            new_name='MachineId',
        ),
    ]
