# Generated by Django 5.0.3 on 2024-07-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0005_rename_machineid_thresholds_machineid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
